from __future__ import annotations

from datetime import datetime
from typing import Protocol

from postify.domain.delivery.models import DeliveryClaim, PublishFailureKind


class DeliveryRepository(Protocol):
    def is_retryable(self, delivery_id: int) -> bool: ...
    def mark_stale_sending_uncertain(self, *, stale_before: datetime, now: datetime) -> int: ...
    def pending_cleanup(self) -> DeliveryClaim | None: ...
    def reserve_next(
        self,
        *,
        now: datetime,
        post_id: int | None = None,
        delivery_id: int | None = None,
    ) -> DeliveryClaim | None: ...
    def record_failure(self, claim: DeliveryClaim, *, kind: PublishFailureKind, code: str, reason: str, now: datetime) -> None: ...
    def confirm_published(self, claim: DeliveryClaim, *, message_id: int, now: datetime) -> None: ...
    def mark_media_deleted(self, delivery_id: int, *, now: datetime) -> None: ...
    def mark_media_retained(self, delivery_id: int, *, now: datetime) -> None: ...
