"""Immutable rich API payload template used by browser_support."""

from __future__ import annotations

import base64

PROJECT = "/api/v1/projects/41"
PIXEL_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
)

FIXTURE_TEMPLATE: dict[str, object] = {
    "/api/v1/bootstrap": {
        "csrfToken": "browser-fixture-capability",
        "activeProject": {"id": 41, "name": "Технологии просто"},
        "providers": {
            "sources": [{
                "code": "hn_algolia",
                "label": "HN Algolia",
                "fields": [
                    {"name": "url", "label": "Адрес API", "type": "url", "required": True, "protocol": "https"},
                    {"name": "query", "label": "Поисковый запрос", "type": "text", "required": True},
                    {"name": "tags", "label": "Теги", "type": "text", "required": True},
                    {"name": "hits", "label": "Материалов за запрос", "type": "number", "required": True, "min": 1, "max": 1000},
                ],
            }],
            "channels": [{
                "code": "telegram",
                "label": "Telegram",
                "fields": [
                    {"name": "chat_id", "label": "@username канала", "type": "text", "required": True, "placeholder": "@aioiai_ai_news"},
                ],
                "credential": {"name": "token", "label": "Токен бота", "input_type": "password"},
            }],
        },
    },
    f"{PROJECT}/dashboard": {
        "candidate_total": 9001,
        "undecided_materials": 3,
        "selected_materials": 8,
        "package_total": 5,
        "approved_packages": 2,
        "published_today": 1,
        "daily_analyses_started": 7,
        "daily_packages_created": 4,
        "manual_analyses_started": 18,
        "manual_packages_created": 6,
        "automaticAnalysisLimit": 12,
        "automaticPackageLimit": 3,
        "deficit": 1,
        "ready_delivery_ids": [9001],
        "signals": [],
        "runtime": {"database": "available", "scheduler": "active"},
        "recent_operations": [{
            "run_id": 9001,
            "operation": "run_once",
            "status": "succeeded",
            "outcome": "completed",
            "failure_code": None,
            "finished_at": "2026-08-12T07:00:12Z",
            "started_at": "2026-08-12T07:00:00Z",
        }],
    },
    f"{PROJECT}/materials": {
        "items": [{
            "candidate_id": 9001,
            "source_name": "Исследовательский блог",
            "title": "Материал 9001 <img src=x onerror=window.__unsafe=1>",
            "url": "https://example.test/material-9001",
            "discovered_at": "2026-08-12T08:15:00Z",
            "decision_status": "selected",
            "decision_reason": "eligible_for_ai",
            "decision_explanation": "Есть практическая польза",
            "decision_signals": {"topic": "ai"},
            "policy_version": "v7",
        }],
    },
    f"{PROJECT}/packages": {
        "items": [{
            "package_id": 9001,
            "status": "awaiting_review",
            "source_url": "https://example.test/material-9001",
            "post_text": "Пакет 9001: полезный разбор",
            "media_available": True,
            "media_status": "available",
            "created_at": "2026-08-12T09:00:00Z",
            "updated_at": "2026-08-12T09:00:00Z",
        }],
    },
    f"{PROJECT}/packages/9001": {
        "package_id": 9001,
        "status": "awaiting_review",
        "source_url": "https://example.test/material-9001",
        "post_text": "Пакет 9001: полезный разбор",
        "analysis": "Полезен для продуктовой команды",
        "media_available": True,
        "media_status": "available",
        "media_source_type": "og",
        "media_source_url": "https://media.example.test/9001.png",
        "history": [{"status": "awaiting_review", "reason": "generated", "created_at": "2026-08-12T09:00:00Z"}],
        "generation_snapshot": {"format": {"name": "Практический разбор"}},
        "created_at": "2026-08-12T09:00:00Z",
        "updated_at": "2026-08-12T09:00:00Z",
    },
    f"{PROJECT}/queue": {
        "items": [{
            "route_id": 9,
            "provider": "telegram",
            "slot_time": "09:30",
            "assignment_kind": "forecast",
            "package_id": 9001,
            "delivery_id": None,
        }],
    },
    f"{PROJECT}/publications": {
        "items": [{
            "delivery_id": 9001,
            "package_id": 8001,
            "provider": "telegram",
            "status": "published",
            "attempt_count": 2,
            "attempts": [
                {"attempt_no": 1, "outcome": "retryable", "code": "telegram_retryable", "message_id": None, "started_at": "2026-08-12T09:55:00Z", "finished_at": "2026-08-12T09:56:00Z"},
                {"attempt_no": 2, "outcome": "published", "code": None, "message_id": 42, "started_at": "2026-08-12T10:00:00Z", "finished_at": "2026-08-12T10:01:00Z"},
            ],
            "message_id": 42,
            "failure_code": None,
            "failure_reason": None,
            "sending_started_at": "2026-08-12T10:00:00Z",
            "confirmed_at": None,
            "created_at": "2026-08-12T10:00:00Z",
            "updated_at": "2026-08-12T10:01:00Z",
        }],
    },
    f"{PROJECT}/operations": {
        "items": [{
            "run_id": 9001,
            "kind": "run_once",
            "status": "succeeded",
            "outcome": "completed",
            "failure_code": None,
            "started_at": "2026-08-12T07:00:00Z",
            "finished_at": "2026-08-12T07:00:12Z",
            "duration": 12,
            "mode": "manual",
            "actor": "ui",
            "codex_model": "gpt-5.6-luna",
            "codex_reasoning_effort": "high",
            "materials_taken": 3,
            "packages_created": 2,
        }],
        "operational": {
            "deficit": 1,
            "signals": [],
            "ready_delivery_ids": [9001],
            "runtime": {"database": "available", "scheduler": "active"},
        },
    },
    f"{PROJECT}/settings": {
        "project": {
            "id": 41,
            "name": "Технологии просто",
            "topic": "Практичные AI-инструменты",
            "language": "ru",
            "audience": "Продуктовые команды",
            "timezone": "Europe/Moscow",
            "configuration": {
                "selection_policy_version": "project-41-v7",
                "selection_rules": ["advertising", "out_of_scope", "hiring", "technical_without_use"],
                "topic_terms": ["ai", "автоматизация"],
                "topic_exclusion_terms": ["лотерея"],
                "advertising_terms": ["реклама"],
                "hiring_terms": ["вакансия"],
                "technical_release_terms": ["release notes"],
                "practical_terms": ["кейс"],
                "selection_freshness_days": 30,
                "daily_analysis_limit": 12,
                "daily_package_limit": 3,
                "priority_freshness_days": 14,
                "fresh_share_percent": 90,
                "reserve_share_percent": 10,
                "review_required": True,
                "article_max_bytes": 2000000,
                "media_max_bytes": 10000000,
                "analysis_timeout_seconds": 600,
                "analysis_model": "gpt-5.6-luna",
                "analysis_reasoning_effort": "high",
            },
        },
        "sources": [{
            "id": 1,
            "provider": "hn_algolia",
            "name": "Новости разработчиков",
            "enabled": True,
            "configuration": {"url": "https://hn.algolia.com", "query": "AI", "tags": "story", "hits": 50},
            "schedule": "0 7 * * *",
        }],
        "formats": [{
            "id": 1,
            "name": "Практический разбор B",
            "kind": "text",
            "instructions": "Хук, польза, ограничение и следующий шаг.",
            "enabled": True,
        }],
        "ctas": [{
            "id": 1,
            "name": "Полезный источник",
            "text": "Открыть источник",
            "link_mode": "source",
            "custom_url": None,
            "enabled": True,
        }],
        "channels": [{
            "id": 1,
            "provider": "telegram",
            "name": "Основной канал",
            "enabled": True,
            "configuration": {"chat_id": "@aioiai_ai_news"},
            "connection_status": "configured",
            "secretConfigured": True,
        }],
        "routes": [{
            "id": 1,
            "format_id": 1,
            "channel_id": 1,
            "cta_id": 1,
            "enabled": True,
            "schedule": {"autopublish": True, "slots": ["09:00", "14:00", "19:00"]},
        }],
    },
}
